reorder_imports = false
reorder_modules = false

control_brace_style = "ClosingNextLine"
condense_wildcard_suffixes = true
binop_separator = "Back"

fn_params_layout = "Compressed"
fn_args_layout = "Compressed"
fn_single_line = true

format_code_in_doc_comments = true
